### PR TITLE
Replace include with #include 

### PR DESCRIPTION
**Pull request by AksharP5**

### CODE REVIEW

**Comment by StoneyJackson** [comment]
Closes #18

**Comment by AksharP5** [comment]
@StoneyJackson Not sure if the .ps files also need to have 'include' replaced with '#include', and in the Heliotis_Slides, there were multiple plcc files with a singular '# include' with the space that was different than the rest, which I left for now, as I wasn't sure if that was meant to be there on purpose or not, just thought I should let you know, also the changes to those files can easily be removed if they are not needed.

**Comment by StoneyJackson** [comment]
@AksharP5 Thanks for the work!

.ps and .pdf files are generated from .tex files (at least in JNote/). So we won't modify them directly. We will regenerate them before this PR is done.

@jashelio You're probably the best judge of Heliotis_Slides . I'll add this to our agenda today.

**Comment by StoneyJackson** [comment]
Commit message

```
refactor: use #include instead of include

---

Closes #18
```

**Pull request merged**
